services:
  mariadb:
    pull_policy: never
    env_file: .env
    environment:
      MARIADB_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
      MARIADB_PASSWORD_FILE: /run/secrets/db_password
    build: 
      context: ./requirements/mariadb
      args:
        ALPINE_VERSION: ${ALPINE_VERSION}
    image: mariadb:1.0
    container_name: mariadb
    restart: unless-stopped
    secrets:
      - db_root_password
      - db_password
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u wordpress -p$$(cat /run/secrets/db_password)"]
      interval: 5s
      timeout: 3s
      retries: 5

  wordpress:
    pull_policy: never
    env_file: .env
    environment:
      WORDPRESS_DB_PASSWORD_FILE: /run/secrets/db_password
      WP_ADMIN_PASSWORD_FILE: /run/secrets/wp_admin_password
      WP_USER_PASSWORD_FILE: /run/secrets/wp_user_password
    build: 
      context: ./requirements/wordpress
      args:
        ALPINE_VERSION: ${ALPINE_VERSION}
    image: wordpress:1.0
    container_name: wordpress
    restart: unless-stopped
    depends_on:
      mariadb:
        condition: service_healthy   # optional, but safe
    secrets:
      - db_password
      - wp_admin_password
      - wp_user_password
    volumes:
      - wordpress_data:/var/www/wordpress
    networks:
      - inception

  nginx:
    pull_policy: never
    env_file: .env
    build:
      context: ./requirements/nginx
      args:
        ALPINE_VERSION: ${ALPINE_VERSION}
    image: nginx:1.0
    container_name: nginx
    restart: unless-stopped
    ports:
      - "443:443"
    depends_on:
      - wordpress
    volumes:
      - wordpress_data:/var/www/wordpress
    networks:
      - inception

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/atambo/data/mariadb
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/atambo/data/wordpress

networks:
  inception:
    driver: bridge

secrets:
  db_root_password:
    file: $HOME/.inception_secrets/db_root_password.txt
  db_password:
    file: $HOME/.inception_secrets/db_password.txt
  wp_admin_password:
    file: $HOME/.inception_secrets/wp_admin_password.txt
  wp_user_password:
    file: $HOME/.inception_secrets/wp_user_password.txt